2025-07-10 16:07:22,872 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 16:20:00,918 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 16:29:50,826 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:25:18,128 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:26:08,096 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:26:31,080 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:26:45,322 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:27:20,690 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:27:41,693 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:28:04,012 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:28:47,923 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:29:09,845 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:44:17,254 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:52:38,939 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:53:33,428 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 18:54:08,462 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 19:09:21,359 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 19:18:20,294 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 19:19:41,048 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 19:23:09,473 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-10 19:28:04,658 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-11 05:56:14,374 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-11 06:02:20,896 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'lon'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.lon},{b.lat};color:blue;text:{i + 1};size:small&"
                      ^^^^^
AttributeError: 'Business' object has no attribute 'lon'
2025-07-11 06:09:52,903 - root - ERROR - Failed to generate map HTML: 'Business' object has no attribute 'longitutde'
Traceback (most recent call last):
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\core\utils.py", line 217, in save_map_html
    markers = "".join(
        f"markers=lonlat:{b.longitutde},{b.latitude};color:blue;text:{i + 1};size:small&"
        for i, b in enumerate(businesses)
    )
  File "C:\Users\1040G7\Documents\INTERNSHIP\NITDA\Python Advance\business_finder\core\utils.py", line 218, in <genexpr>
    f"markers=lonlat:{b.longitutde},{b.latitude};color:blue;text:{i + 1};size:small&"
                      ^^^^^^^^^^^^
AttributeError: 'Business' object has no attribute 'longitutde'. Did you mean: 'longitude'?
2025-07-11 09:31:35,482 - root - ERROR - API request failed in make_api_request: HTTPSConnectionPool(host='api.geoapify.com', port=443): Max retries exceeded with url: /v2/places?categories=catering&filter=circle%3A7.36%2C9.14%2C10000&bias=proximity%3A7.36%2C9.14&limit=20&apiKey=507aeb6573834255b59f2f6896cbd684 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001856C2EDE50>: Failed to resolve 'api.geoapify.com' ([Errno 11001] getaddrinfo failed)"))
2025-07-11 09:31:35,545 - root - WARNING - Retry 1/3 for make_api_request after 1.0s
